// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafxhLSZCLBCeZts9-kMr4FgMaBNSeFfM',
    appId: '1:328832504007:web:229d2ea3c3642cec5a2ee2',
    messagingSenderId: '328832504007',
    projectId: 'burger-house-d15a1',
    authDomain: 'burger-house-d15a1.firebaseapp.com',
    storageBucket: 'burger-house-d15a1.appspot.com',
    measurementId: 'G-VDM3XYZHZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKngltRDGQ0IpjKGG1B4AiXLAWnvrDyww',
    appId: '1:328832504007:android:44756b543a6dcf935a2ee2',
    messagingSenderId: '328832504007',
    projectId: 'burger-house-d15a1',
    storageBucket: 'burger-house-d15a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUb-zDh6OvjjX3aXF5UATaKy_hZA9Kby4',
    appId: '1:328832504007:ios:622a4191940f8c305a2ee2',
    messagingSenderId: '328832504007',
    projectId: 'burger-house-d15a1',
    storageBucket: 'burger-house-d15a1.appspot.com',
    iosBundleId: 'com.example.burgerHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUb-zDh6OvjjX3aXF5UATaKy_hZA9Kby4',
    appId: '1:328832504007:ios:622a4191940f8c305a2ee2',
    messagingSenderId: '328832504007',
    projectId: 'burger-house-d15a1',
    storageBucket: 'burger-house-d15a1.appspot.com',
    iosBundleId: 'com.example.burgerHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCafxhLSZCLBCeZts9-kMr4FgMaBNSeFfM',
    appId: '1:328832504007:web:569b900a26917dbe5a2ee2',
    messagingSenderId: '328832504007',
    projectId: 'burger-house-d15a1',
    authDomain: 'burger-house-d15a1.firebaseapp.com',
    storageBucket: 'burger-house-d15a1.appspot.com',
    measurementId: 'G-VVNFXS7NVS',
  );
}
